name: dropsource_utils
description: A set of useful functions and libraries used in almost all
  Dropsource flutter apps.
version: 0.0.3+4
author: Nathan Frechette<nate@dropsource.com>
homepage: https://dropsource.com

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  auto_size_text: ^2.1.0
  build_context: ^2.0.4
  dio: ^3.0.10
  firebase_analytics: ^6.1.0
  firebase_core: ^0.5.1
  firebase_crashlytics: ^0.2.2
  flutter_email_sender: ^3.0.1
  intl: ^0.16.1
  logging: ^0.11.4
  provider: ^4.3.2+2
  rxdart: ^0.24.1
  url_launcher: ^5.7.8

dev_dependencies:
  flutter_test:
    sdk: flutter
