name: dropsource_utils
description: A set of useful functions and libraries used in almost all Dropsource flutter apps.
version: 0.0.3+4
author: Nathan Frechette<nate@dropsource.com>
homepage: https://dropsource.com

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  dio: ^3.0.9
  firebase_core: ^0.4.5
  firebase_analytics: ^5.0.16
  firebase_crashlytics: ^0.1.3+3
  # firebase_crashlytics:
  # path: /Users/Shared/Developer/git/flutterfire/packages/firebase_crashlytics
  rxdart: ^0.24.1
  provider: ^4.3.1
  auto_size_text: ^2.1.0
  build_context: ^2.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter
