name: dropsource_utils
description: A set of useful functions and libraries used in almost all
  Dropsource flutter apps.
version: 0.0.3+5
author: Nathan Frechette<nate@dropsource.com>
homepage: https://dropsource.com

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  auto_size_text: ^3.0.0-nullsafety.0
  build_context: ^3.0.0
  dio: ^4.0.0
  equatable: ^2.0.3
  firebase_analytics: ^8.3.1
  firebase_core: ^1.6.0
  firebase_crashlytics: ^2.2.1
  flutter:
    sdk: flutter
  flutter_email_sender: ^5.0.2
  intl: ^0.17.0
  logging: ^1.0.1
  provider: ^6.0.0
  rxdart: ^0.27.1
  url_launcher: ^6.0.9

dev_dependencies:
  flutter_test:
    sdk: flutter
