name: ds_crashlytics
description: A set of useful functions and libraries used in almost all
  Dropsource flutter apps.
version: 1.0.0
homepage: https://dropsource.com
publish_to: none

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  firebase_crashlytics: ^2.8.4
  flutter_riverpod: ^1.0.4
