name: ds_utils
description: A set of useful functions and libraries used in almost all
  Dropsource flutter apps.
version: 1.0.0
homepage: https://dropsource.com
publish_to: none

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  equatable: ^2.0.5
  freezed_annotation: ^2.1.0
  intl: ^0.17.0
  ms_map_utils: ^1.1.0
  rxdart: ^0.27.5

dev_dependencies:
  build_runner: ^2.2.0
  freezed: ^2.1.0+1
