name: ds_utils
description: A set of useful functions and libraries used in almost all
  Dropsource flutter apps.
version: 1.0.0
homepage: https://dropsource.com
publish_to: none

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  cross_file: ^0.3.4+1
  dio: ^5.4.1
  freezed_annotation: ^2.4.1
  intl: ^0.18.1
  sentry_dio: ^7.18.0
  riverpod: ^2.5.1
  riverpod_annotation: ^2.3.5
  rxdart: ^0.27.7
  uuid: ^4.3.3

dev_dependencies:
  build_runner: ^2.4.7
  freezed: ^2.4.7
  riverpod_generator: ^2.4.0
