name: ds_utils
description: A set of useful functions and libraries used in almost all
  Dropsource flutter apps.
version: 1.0.0
homepage: https://dropsource.com
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  dartz: ^0.10.1
  dio: ^5.4.0
  equatable: ^2.0.5
  freezed_annotation: ^2.4.1
  intl: ^0.19.0
  ms_map_utils: ^1.1.0
  rxdart: ^0.27.7

dev_dependencies:
  build_runner: ^2.4.7
  freezed: ^2.4.6
