name: dropsource_ui
description: A set of useful functions and libraries used in almost all
  Dropsource flutter apps.
version: 0.0.4+1
homepage: https://dropsource.com
publish_to: none

environment:
  sdk: ">=2.15.0 <3.0.0"

dependencies:
  auto_size_text: ^3.0.0
  build_context: ^3.0.0
  connectivity_plus: ^2.3.0
  dio: ^4.0.4
  dropsource_core:
    git:
      url: https://github.com/Dropsource/flutter_utils.git
      path: core
      ref: riverpod
  firebase_analytics: ^9.1.8
  firebase_core: ^1.17.0
  firebase_crashlytics: ^2.8.0
  flutter:
    sdk: flutter
  flutter_riverpod: ^1.0.4
  go_router: ^3.1.0
  logging: ^1.0.2
  url_launcher: ^6.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
