name: dropsource_ui
description: A set of useful functions and libraries used in almost all
  Dropsource flutter apps.
version: 0.0.3+5
homepage: https://dropsource.com
publish_to: none

environment:
  sdk: ">=2.15.0 <3.0.0"

dependencies:
  auto_size_text: ^3.0.0
  build_context: ^3.0.0
  connectivity_plus: ^3.0.2
  dio: ^4.0.4
  dropsource_core:
    git:
      url: https://github.com/Dropsource/flutter_utils.git
      path: core
      ref: refactor
  firebase_analytics: ^10.0.7
  firebase_core: ^2.4.0
  firebase_crashlytics: ^3.0.7
  flutter:
    sdk: flutter
  logging: ^1.0.2
  provider: ^6.0.2
  url_launcher: ^6.1.7

dev_dependencies:
  flutter_test:
    sdk: flutter
