name: ds_ui
description: A set of useful functions and libraries used in almost all
  Dropsource flutter apps.
version: 0.0.4+1
homepage: https://dropsource.com
publish_to: none

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  auto_size_text: ^3.0.0
  build_context: ^3.0.0
  connectivity_plus: ^2.3.9
  dartz: ^0.10.1
  dio: ^4.0.6
  ds_utils:
    git:
      url: https://github.com/Dropsource/flutter_utils.git
      path: utils
      ref: dev
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.0.2
  freezed_annotation: ^2.2.0
  logging: ^1.1.0
  sentry_flutter: ^6.13.0
  url_launcher: ^6.1.6

dev_dependencies:
  build_runner: ^2.2.1
  flutter_test:
    sdk: flutter
  freezed: ^2.1.1
