name: ds_ui
description: A set of useful functions and libraries used in almost all
  Dropsource flutter apps.
version: 0.0.4+1
homepage: https://dropsource.com
publish_to: none

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  auto_size_text: ^3.0.0
  build_context: ^3.0.0
  connectivity_plus: ^2.3.4
  dio: ^4.0.6
  ds_utils:
    git:
      url: https://github.com/Dropsource/flutter_utils.git
      path: utils
      ref: dev
  flutter:
    sdk: flutter
  flutter_riverpod: ^1.0.4
  freezed_annotation: ^2.0.3
  logging: ^1.0.2
  url_launcher: ^6.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.1.11
  freezed: ^2.0.3+1
