name: ds_ui
description: A set of useful functions and libraries used in almost all
  Dropsource flutter apps.
version: 0.0.4+1
homepage: https://dropsource.com
publish_to: none

environment:
  sdk: ">=2.19.0 <3.0.0"

dependencies:
  auto_size_text: ^3.0.0
  dartz: ^0.10.1
  dio: ^5.1.2
  ds_utils:
    git:
      url: https://github.com/Dropsource/flutter_utils.git
      path: utils
      ref: dev
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.3.5
  freezed_annotation: ^2.2.0
  logging: ^1.1.1
  sentry_flutter: ^7.6.2
  url_launcher: ^6.1.11

dev_dependencies:
  build_runner: ^2.3.3
  flutter_test:
    sdk: flutter
  freezed: ^2.3.3
