name: dropsource_ui
description: A set of useful functions and libraries used in almost all
  Dropsource flutter apps.
version: 0.0.3+5
homepage: https://dropsource.com
publish_to: none

environment:
  sdk: ">=2.14.0 <3.0.0"

dependencies:
  auto_size_text: ^3.0.0-nullsafety.0
  build_context: ^3.0.0
  connectivity_plus: ^2.0.2
  dio: ^4.0.0
  dropsource_core:
    git:
      url: https://github.com/Dropsource/flutter_utils.git
      path: core
      ref: refactor
  firebase_analytics: ^8.3.3
  firebase_core: ^1.7.0
  firebase_crashlytics: ^2.2.3
  flutter:
    sdk: flutter
  logging: ^1.0.2
  provider: ^6.0.1
  url_launcher: ^6.0.12

dev_dependencies:
  flutter_test:
    sdk: flutter
