name: dropsource_ui
description: A set of useful functions and libraries used in almost all
  Dropsource flutter apps.
version: 0.0.3+5
homepage: https://dropsource.com
publish_to: none

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  auto_size_text: ^3.0.0
  build_context: ^3.0.0
  connectivity_plus: ^3.0.4
  dio: ^5.1.1
  dropsource_core:
    git:
      url: https://github.com/Dropsource/flutter_utils.git
      path: core
      ref: master
  firebase_analytics: ^10.2.1
  firebase_core: ^2.10.0
  firebase_crashlytics: ^3.1.1
  flutter:
    sdk: flutter
  logging: ^1.1.0
  provider: ^6.0.5
  url_launcher: ^6.1.10

dev_dependencies:
  flutter_test:
    sdk: flutter
