name: dropsource_ui
description: A set of useful functions and libraries used in almost all
  Dropsource flutter apps.
version: 0.0.3+5
author: Nathan Frechette<nate@dropsource.com>
homepage: https://dropsource.com
publish_to: none

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  dropsource_core:
    git:
      url: https://github.com/Dropsource/flutter_utils.git
      path: core
      ref: refactor
  auto_size_text: ^3.0.0-nullsafety.0
  build_context: ^3.0.0
  dio: ^4.0.0
  firebase_analytics: ^8.3.1
  firebase_core: ^1.6.0
  firebase_crashlytics: ^2.2.1
  flutter:
    sdk: flutter
  flutter_email_sender: ^5.0.2
  logging: ^1.0.1
  provider: ^6.0.0
  url_launcher: ^6.0.9

dev_dependencies:
  flutter_test:
    sdk: flutter
